// <auto-generated />
namespace ME_BlogProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modeltest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modeltest));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221829221_modeltest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
